### ISSUE TITLE
您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及侵权，麻烦您将这个仓库删除，谢谢您的配合

### ISSUE THREAD

**Issue by griabcrh** [github-doming/vue-life-cycle#1]
您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及侵权，麻烦您将这个仓库删除，谢谢您的配合

**Comment by github-doming** [comment]
已删除

**Comment by github-doming** [comment]
> 您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及侵权，麻烦您将这个仓库删除，谢谢您的配合



> 您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及错误，麻烦您将这个仓库删除，谢谢您的配合

**Comment by griabcrh** [comment]
好的，感谢您的支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-doming/vue-life-cycle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [github-doming/vue-life-cycle] 您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及侵权，麻烦您将这个仓库删除，谢谢您的配合 (#1)





 
已删除
